mirte_bringup:
  ubuntu:
  - ros-humble-mirte-bringup
mirte_msgs:
  ubuntu:
  - ros-humble-mirte-msgs
mirte_base_control:
  ubuntu:
  - ros-humble-mirte-base-control
mirte_control:
  ubuntu:
  - ros-humble-mirte-control
mirte_telemetrix_cpp:
  ubuntu:
  - ros-humble-mirte-telemetrix-cpp
mirte_teleop:
  ubuntu:
  - ros-humble-mirte-teleop
web_video_server:
  ubuntu:
  - ros-humble-web-video-server
